name: qr_pay_app
description: "A new Flutter project."

publish_to: "none"

version: 1.1.8+58

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Layout
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.2.3
  flutter_launcher_icons: ^0.12.0
  flutter_svg: ^1.0.3
  spider: ^4.2.1
  carousel_slider: ^5.0.0
  extended_masked_text: ^2.3.1
  image_picker: ^1.0.4
  shimmer: ^3.0.0
  intl: ^0.20.2
  dropdown_button2: ^2.3.9
  table_calendar: ^3.0.9
  file_picker:
  package_info_plus: ^8.3.0
  mask_text_input_formatter: ^2.4.0
  flutter_keyboard_visibility: ^6.0.0
  photo_view: ^0.15.0
  smooth_page_indicator: ^1.2.0+3
  # liquid_glass_renderer: ^0.1.1-dev.6
  google_fonts: ^4.0.4
  grouped_list: ^6.0.0
  flutter_staggered_grid_view: ^0.7.0
  video_player: ^2.9.2
  lottie: ^3.0.0
  # flutter_story_presenter: ^1.0.4
  flutter_story_presenter:
    git:
      url: https://github.com/Alibalishka/flutter_stories.git
  # story:
  #   git:
  #     url: https://github.com/Alibalishka/story.git
  flutter_phoenix: ^1.1.1
  torch_light: ^1.1.0
  # Translations
  easy_localization: ^3.0.7
  # Navigation
  auto_route: ^5.0.1
  # Rest API and State management
  flutter_bloc: ^8.1.1
  bloc_concurrency: ^0.2.5
  dio: ^5.3.2
  json_annotation: ^4.7.0
  provider: ^6.1.1
  meta: ^1.9.1
  bloc: ^8.1.2
  freezed_annotation: ^2.1.0
  get_it: ^7.6.7
  talker_flutter:
  talker_dio_logger:
  # Local storage
  shared_preferences: ^2.0.6
  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # Location
  geolocator: ^11.0.0
  # Yandex Map
  yandex_mapkit:
    git:
      url: https://github.com/muhammadyunusxon/yandex_mapkit.git
  yandex_geocoder:
  # Barcode
  # qr_code_scanner: ^1.0.1
  qr_code_scanner_plus: ^2.0.10+1
  # Utilities
  connectivity_plus:
  l: ^3.1.0
  url_launcher: ^6.2.4
  # Firebase
  # firebase_core: ^3.4.0
  # firebase_analytics: ^11.0.0
  # firebase_messaging: ^15.1.0
  # flutter_local_notifications: ^18.0.1
  # flutter_app_badge: ^2.0.2
  # app_links: ^6.3.2
  # Pay
  # pay: ^2.0.0
  # flutter_stripe: 11.0.0
  share_plus: ^10.1.4
  # Update app
  upgrader:
  vibration: ^3.1.2
  flutter_inappwebview: ^6.1.5
  # webview_flutter: ^4.7.0
  # webview_flutter_wkwebview: ^3.10.0
  device_info_plus: ^10.1.2
  battery_plus: ^6.2.1
  network_info_plus: ^6.1.4
  qr_flutter: ^4.1.0
  sizer: ^3.1.3
  modal_bottom_sheet: ^3.0.0
  # ota_update: ^7.1.0
  flutter_cache_manager: ^3.3.1
  crypto: ^3.0.3
  flutter_secure_storage: ^9.0.0
  uuid: ^4.4.0
  path_provider: ^2.1.2
  path: ^1.9.0
  internet_connection_checker: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  # hive_generator: ^2.0.1
  freezed: ^2.1.0+1

flutter:
  uses-material-design: true

  assets:
    # - assets/images/png/
    - assets/images/svg/
    - assets/images/webp/
    - assets/translations/
    - assets/lottie/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish/Mulish-BlackItalic.ttf

        - asset: assets/fonts/Mulish/Mulish-Bold.ttf
        - asset: assets/fonts/Mulish/Mulish-BoldItalic.ttf

        - asset: assets/fonts/Mulish/Mulish-ExtraBold.ttf
        - asset: assets/fonts/Mulish/Mulish-ExtraBoldItalic.ttf

        - asset: assets/fonts/Mulish/Mulish-ExtraLight.ttf
        - asset: assets/fonts/Mulish/Mulish-ExtraLightItalic.ttf

        - asset: assets/fonts/Mulish/Mulish-Italic.ttf

        - asset: assets/fonts/Mulish/Mulish-Light.ttf
        - asset: assets/fonts/Mulish/Mulish-LightItalic.ttf

        - asset: assets/fonts/Mulish/Mulish-Medium.ttf
        - asset: assets/fonts/Mulish/Mulish-MediumItalic.ttf

        - asset: assets/fonts/Mulish/Mulish-Regular.ttf

        - asset: assets/fonts/Mulish/Mulish-SemiBold.ttf
        - asset: assets/fonts/Mulish/Mulish-SemiBoldItalic.ttf
